# Generated by Django 6.0 on 2025-12-10 19:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("label", models.CharField(default="person", max_length=100)),
                ("confidence", models.FloatField()),
                ("image_path", models.CharField(max_length=500)),
                ("resolved", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "resolved"],
                        name="monitoring__timesta_fa062f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DetectionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_detections", models.IntegerField(default=0)),
                ("total_alerts", models.IntegerField(default=0)),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence_threshold", models.FloatField(default=0.4)),
                ("detection_enabled", models.BooleanField(default=False)),
                ("alert_sound_enabled", models.BooleanField(default=True)),
                ("email_alerts_enabled", models.BooleanField(default=False)),
                ("sms_alerts_enabled", models.BooleanField(default=False)),
                ("alert_email", models.EmailField(blank=True, max_length=254)),
                ("alert_phone", models.CharField(blank=True, max_length=20)),
                ("min_detection_confidence", models.FloatField(default=0.4)),
                ("alert_cooldown_seconds", models.IntegerField(default=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("dataset_path", models.CharField(max_length=500)),
                ("model_name", models.CharField(default="yolov8n", max_length=100)),
                ("epochs", models.IntegerField(default=50)),
                ("batch_size", models.IntegerField(default=8)),
                ("image_size", models.IntegerField(default=640)),
                ("progress", models.IntegerField(default=0)),
                ("logs", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
