# Generated by Django 4.2.23 on 2025-12-11 07:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_authorizedperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizedperson",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="authorizedperson",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="authorizedperson",
            name="role",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="AuthorizedPersonPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="authorized_persons/additional/"),
                ),
                ("face_encoding", models.TextField(blank=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_photos",
                        to="monitoring.authorizedperson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Photo",
                "verbose_name_plural": "Additional Photos",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
