# Generated by Django 4.2.23 on 2025-12-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_authorizedperson_email_authorizedperson_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorizedperson",
            name="employee_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
